// The Pages build supplies config.json. Private state remains in this browser's IndexedDB.
import {mergePositions} from './lib.js';
const DB_NAME='ark-agent-private-v1';
let dbPromise;
async function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('此瀏覽器無法使用本機儲存，請允許網站資料儲存。'));});return dbPromise;}
async function get(key){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('records').objectStore('records').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function put(key,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('records','readwrite');tx.objectStore('records').put(value,key);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(new Error('瀏覽器儲存失敗；請檢查可用空間。'));tx.onabort=()=>reject(new Error('瀏覽器儲存未完成。'));});}
const copy=v=>structuredClone(v);
const now=()=>new Date().toISOString();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function validDate(v,nullable=false){if(v===null&&nullable)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(v||'')||Number.isNaN(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw new Error('日期須為有效 YYYY-MM-DD');return v;}
function number(v){if(v===null)return null;if(typeof v!=='number'||!Number.isFinite(v))throw new Error('數值須為有限數值或 null');return v;}
function position(p){const code=String(p.code||'').trim().toUpperCase();if(!/^[A-Z0-9.^-]{1,20}$/.test(code))throw new Error('股票代號無效');const out={code,name:String(p.name||''),note:String(p.note||'')};for(const k of ['shares','ret','pnl','value'])out[k]=number(p[k]??null);if((out.shares??0)<0||(out.value??0)<0)throw new Error('數量與市值不可為負');if(!out.note&&['shares','ret','pnl','value'].some(k=>out[k]===null))out.note='未提供的欄位待更新。';return out;}
function portfolio(p){validDate(p.asOf,true);number(p.totalPnl);if(!Number.isInteger(p.day)||p.day<0)throw new Error('Day 必須是非負整數');if(!p.rules||['p1','p3','p2'].some(k=>typeof p.rules[k]!=='number'||!Number.isFinite(p.rules[k]))||!(p.rules.p1<p.rules.p3&&p.rules.p3<p.rules.p2))throw new Error('請維持 P1 < P3 < P2');if(!Array.isArray(p.positions)||p.positions.length>500)throw new Error('持股格式錯誤');const ps=p.positions.map(position);if(new Set(ps.map(x=>x.code)).size!==ps.length)throw new Error('持股代號重複');return {...p,positions:ps};}
const aliases={code:['code','代號','股票代號','證券代號','商品代號'],name:['name','名稱','股票名稱','證券名稱','商品名稱'],shares:['shares','股數','庫存股數','持有數量','數量'],ret:['ret','報酬率','報酬率(%)','報酬率％','報酬率%','損益率','損益率(%)'],pnl:['pnl','損益','未實現損益','預估損益'],value:['value','市值','現值','參考市值'],asOf:['asOf','日期','資料日期','對帳日期'],totalPnl:['totalPnl','總損益','總未實現損益'],note:['note','備註']};
export function parseNumber(v){let s=String(v??'').trim().replace(/[,，%％]/g,'').replace(/−/g,'-');if(['','-','--','N/A','null','待更新'].includes(s))return null;if(s.startsWith('(')&&s.endsWith(')'))s='-'+s.slice(1,-1);if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s))throw new Error('無法辨識數值：'+s.slice(0,40));return number(Number(s));}
// CSV quoting, escaped quotes and embedded newlines. TSV uses the same parser.
export function csvRows(text,delimiter=','){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else cell+=c;}else if(c===delimiter&&!quoted){row.push(cell);cell='';}else if((c==='\r'||c==='\n')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('CSV 引號未閉合');row.push(cell);if(row.some(v=>v.trim()))rows.push(row);return rows;}
export function parseCSV(text){text=text.replace(/^\ufeff/,'');const lines=text.split(/\r?\n/);const start=lines.findIndex(l=>aliases.code.some(a=>l.includes(a)));if(start<0)throw new Error('未找到標準代號欄；非標準文字須使用本機 AI 版。');const part=lines.slice(start).join('\n'),rows=csvRows(part,lines[start].includes('\t')?'\t':',');const headers=rows.shift();const keys=Object.fromEntries(Object.entries(aliases).map(([k,a])=>[k,headers.findIndex(x=>a.includes(x.trim()))]));if(keys.code<0)throw new Error('未找到標準代號欄');const out={asOf:null,totalPnl:null,positions:[],note:'瀏覽器直接擷取標準欄位；未推算缺值。ret 使用百分比數值。'};for(const row of rows){const v=Object.fromEntries(Object.entries(keys).map(([k,i])=>[k,i<0?'':row[i]||'']));if(v.asOf.trim()){let d=v.asOf.trim().replaceAll('/','-');const parts=d.split('-').map(Number);if(parts.length===3&&parts.every(Number.isInteger)){const [y,m,dd]=parts;d=`${y<1911?y+1911:y}-${String(m).padStart(2,'0')}-${String(dd).padStart(2,'0')}`;}validDate(d);if(out.asOf&&out.asOf!==d)throw new Error('同一檔案含不同日期，請拆開匯入');out.asOf=d;}if(v.totalPnl.trim())out.totalPnl=parseNumber(v.totalPnl);const code=v.code.trim().replace(/^['"]|['"]$/g,'');if(!code)continue;if(['合計','總計','TOTAL'].includes(code)){if(v.pnl.trim())out.totalPnl=parseNumber(v.pnl);continue;}const p={code,name:v.name,note:v.note};for(const k of ['shares','ret','pnl','value'])p[k]=parseNumber(v[k]);out.positions=mergePositions(out.positions,[position(p)]);}return out;}
export function importPortfolio(current,incoming,mode,older){if(!['merge','replace'].includes(mode))throw new Error('請選擇更新方式');validDate(incoming.asOf);if(current.asOf&&incoming.asOf<current.asOf&&older!=='accept')throw new Error('日期較舊，須明確選擇接受');if(!incoming.positions?.length)throw new Error('沒有可更新持股');const out={...current,asOf:incoming.asOf,day:current.day+(current.asOf&&incoming.asOf>current.asOf?1:0),positions:mode==='merge'?mergePositions(current.positions,incoming.positions.map(position)):mergePositions([],incoming.positions.map(position)),totalPnl:number(incoming.totalPnl??null),note:'使用者已確認匯入；'+(incoming.note||'')};if(mode==='merge'&&out.totalPnl===null){out.totalPnl=current.totalPnl;out.note+=`；總損益沿用 ${current.asOf}，待核對。`;}if(current.asOf&&incoming.asOf<current.asOf)out.note+='；已接受較舊日期，保留 Day。';return portfolio(out);}
async function readPublic(path){const r=await fetch(new URL(path,location.href),{cache:'no-store'});if(!r.ok)throw new Error('公開盤勢查不到／待更新');return r.json();}
async function initialPortfolio(){let p=await get('portfolio');if(!p){p=await readPublic('data/portfolio.initial.json');await put('portfolio',p);}return copy(p);}
async function savePortfolio(p){p=portfolio(p);const old=await initialPortfolio();const history=await get('history')||[];history.unshift(old);p.updatedAt=now();await put('history',history.slice(0,100));await put('portfolio',p);return copy(p);}
export async function staticAPI(path,data,method='POST'){
 if(path==='/api/status')return {aiConfigured:false,mode:'pages',model:null,csrfToken:null,timezone:'Asia/Taipei',today:today(),schedule:{provider:'GitHub Actions',hour:7,minute:52,status:'configured'}};
 if(path==='/crew.json')return readPublic('crew.json');
 if(path==='/api/portfolio')return data===undefined?initialPortfolio():savePortfolio(data);
 if(path==='/api/portfolio/previous'){const p=await initialPortfolio();return (await get('history')||[]).filter(x=>x.asOf&&p.asOf&&x.asOf<p.asOf).sort((a,b)=>b.asOf.localeCompare(a.asOf))[0]||null;}
 if(path.startsWith('/api/briefs?')||path==='/api/briefs')return readPublic('data/briefs/index.json');
 if(path==='/api/briefs/run')return {status:'refreshed'};
 if(path.startsWith('/api/briefs/')){const date=path.split('/').pop();validDate(date);return readPublic('data/briefs/'+date+'.json');}
 if(path==='/api/avatars'){let avatars=await get('avatars')||{};if(data!==undefined){if(!['buffett','marks','dalio','druckenmiller','wood','huang','wei','nadella'].includes(data.id))throw new Error('人物 ID 無效');if(method==='DELETE')delete avatars[data.id];else{if(data.data.length>540000)throw new Error('頭像過大');avatars[data.id]='data:image/jpeg;base64,'+data.data;}await put('avatars',avatars);}return copy(avatars);}
 if(path==='/api/uploads'){const binary=atob(data.data),bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));if(bytes.length>10*1024*1024)throw new Error('每檔上限 10 MB');const id=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');const ext=data.name.split('.').pop().toLowerCase();const meta={id,name:data.name,size:bytes.length,media_type:{png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',csv:'text/plain',tsv:'text/plain',txt:'text/plain'}[ext]};if(!meta.media_type)throw new Error('不支援此格式');if(meta.media_type==='text/plain'){try{meta.text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);meta.encoding='UTF-8';}catch{try{meta.text=new TextDecoder('big5',{fatal:true}).decode(bytes);meta.encoding='Big5';}catch{throw new Error('無法使用 UTF-8 或 Big5 解碼');}}}await put('upload:'+id,meta);return meta;}
 if(path==='/api/import/preview'){const result={asOf:null,totalPnl:null,positions:[],note:''};const parts=[];for(const id of new Set(data.files||[])){const f=await get('upload:'+id);if(!f)throw new Error('找不到匯入檔案');if(f.media_type!=='text/plain')throw new Error('線上版尚未接 AI 後端，截圖辨識待啟用。');parts.push([f.name,f.text]);}if(data.text)parts.push(['貼上文字',data.text]);for(const [name,text] of parts){const p=parseCSV(text);if(p.asOf&&result.asOf&&p.asOf!==result.asOf)throw new Error('檔案日期不一致，請分開匯入');if(p.asOf)result.asOf=p.asOf;if(p.totalPnl!==null)result.totalPnl=p.totalPnl;result.positions=mergePositions(result.positions,p.positions);result.note+=name+'：'+p.note+'\n';}if(!result.positions.length)throw new Error('未找到可匯入持股');return result;}
 if(path==='/api/import/commit'){const p=await initialPortfolio();if(data.baseUpdatedAt!==p.updatedAt)throw new Error('庫存已在別處變更，請重新預覽');return savePortfolio(importPortfolio(p,data.preview,data.mode,data.older));}
 if(path==='/api/journal')return (await get('journals')||[]).sort((a,b)=>b.date.localeCompare(a.date));
 if(path.startsWith('/api/journal/')){validDate(data.date);const rows=await get('journals')||[];const j={...data,createdAt:now()};await put('journals',[j,...rows.filter(x=>x.date!==j.date)]);return j;}
 throw new Error('線上版尚未接 AI 後端，請使用本機 AI 版。');
}
export async function exportPrivate(){return {format:'ark-agent-browser-backup',version:1,exportedAt:now(),portfolio:await initialPortfolio(),avatars:await get('avatars')||{},history:await get('history')||[],journals:await get('journals')||[]};}
export async function restorePrivate(obj){if(obj.format!=='ark-agent-browser-backup'||obj.version!==1)throw new Error('不是有效的方舟瀏覽器備份');portfolio(obj.portfolio);await put('portfolio',obj.portfolio);await put('avatars',obj.avatars||{});await put('history',obj.history||[]);await put('journals',obj.journals||[]);}
