/* Local browser acceptance. AI is mocked ONLY inside this isolated browser test. */
const {chromium}=require(process.env.ARK_PLAYWRIGHT||'playwright');
const {spawn,spawnSync}=require('node:child_process');const fs=require('node:fs');const path=require('node:path');const os=require('node:os');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ark-ui-')),url='http://127.0.0.1:18765';
for(const d of ['briefs','uploads','avatars','history','journal','cache','logs'])fs.mkdirSync(path.join(tmp,d));
fs.copyFileSync(path.join(root,'data/portfolio.initial.json'),path.join(tmp,'portfolio.json'));
const brief=JSON.parse(fs.readFileSync(path.join(root,'public/briefs/2026-10-08.json')));
fs.writeFileSync(path.join(tmp,'briefs/2026-10-08.json'),JSON.stringify(brief));
const old={...brief,date:'2026-10-07',headline:'僅供自動化驗收的歷史資料'};fs.writeFileSync(path.join(tmp,'briefs/2026-10-07.json'),JSON.stringify(old));
spawnSync('python3',['-c',`from pathlib import Path;Path(${JSON.stringify(path.join(tmp,'big5.csv'))}).write_bytes('代號,名稱,報酬率,未實現損益,日期\\n0056,元大高股息,5,0,2026-10-08'.encode('big5'))`]);
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZioAAAAASUVORK5CYII=','base64');fs.writeFileSync(path.join(tmp,'a.png'),png);fs.writeFileSync(path.join(tmp,'duplicate.png'),png);
const server=spawn('python3',[path.join(root,'server.py'),'--port','18765'],{env:{...process.env,ARK_DATA_DIR:tmp,AI_PROVIDER:'',OPENAI_API_KEY:'',ANTHROPIC_API_KEY:''},stdio:'ignore'});let browser;const checks=[],errors=[];
const pass=(label)=>{checks.push(label);console.log('PASS',label);};
async function waitForServer(){for(let i=0;i<50;i++){try{if((await fetch(url+'/api/status')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('test server startup failed');}
(async()=>{await waitForServer();browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForSelector('.crew-card');assert.equal(await page.locator('.crew-card').count(),8);pass('market renders all eight crew');
await page.selectOption('#brief-date','2026-10-07');await page.waitForFunction(()=>document.querySelector('.hero h2').textContent.includes('驗收'));await page.selectOption('#brief-date','2026-10-08');pass('history date selector');
await page.click('[data-filter="ceo"]');assert.equal(await page.locator('.crew-card').count(),3);await page.click('[data-filter="all"]');assert.equal(await page.locator('.crew-card').count(),8);await page.click('[data-person="buffett"]');assert.ok(await page.locator('#crew-buffett').evaluate(e=>e.classList.contains('selected')));assert.equal(await page.locator('#crew-buffett details').getAttribute('open'),'');pass('filters, compass selection, details');
const avatarPng=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=480;const x=c.getContext('2d');x.fillStyle='#8C5E14';x.fillRect(0,0,640,480);return c.toDataURL('image/png').split(',')[1];});fs.writeFileSync(path.join(tmp,'a.png'),Buffer.from(avatarPng,'base64'));fs.writeFileSync(path.join(tmp,'duplicate.png'),Buffer.from(avatarPng,'base64'));await page.click('[data-photo="buffett"]');await page.setInputFiles('#photo-file',{name:'test-avatar.png',mimeType:'image/png',buffer:Buffer.from(avatarPng,'base64')});await page.waitForFunction(()=>!document.querySelector('#photo-save').disabled);await page.click('#photo-save');await page.waitForFunction(()=>document.querySelector('#crew-buffett img').getAttribute('src').startsWith('/data/avatars'));assert.equal(await page.locator('#crew-buffett img').evaluate(e=>e.naturalWidth),400);await page.locator('#crew-buffett summary').click();await page.click('[data-restore="buffett"]');await page.waitForFunction(()=>document.querySelector('#crew-buffett img').getAttribute('src').includes('/assets/'));pass('photo crops to 400px JPEG, syncs and restores');
await page.click('[data-tab="portfolio"]');assert.equal(await page.locator('.position-row').count(),18);assert.match(await page.locator('#portfolio-notice').innerText(),/講義初始資料/);assert.match(await page.locator('[data-account=unrealized]').innerText(),/持股加總|已知持股/);assert.match(await page.locator('[data-account=unrealized]').innerText(),/18/);pass('18 original positions, calculated P&L coverage and sample label');
await page.click('#upload-open');await page.setInputFiles('#statement-files',[path.join(tmp,'big5.csv'),path.join(tmp,'a.png'),path.join(tmp,'duplicate.png')]);await page.waitForFunction(()=>document.querySelector('#upload-progress').textContent.includes('略過 1'));assert.equal(await page.locator('.file-row').count(),2);pass('mixed Big5 CSV and duplicate screenshots deduplicated');
await page.click('#recognize');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('未設定'));pass('missing key blocks image recognition clearly');
await page.locator('.file-row').filter({hasText:'a.png'}).locator('button').click();await page.click('#recognize');await page.waitForSelector('#import-preview:not([hidden])');assert.match(await page.locator('#import-positions').innerText(),/元大高股息/);assert.equal(await page.locator('input[name="import-mode"]:checked').inputValue(),'merge');await page.click('#commit-import');await page.waitForFunction(()=>document.querySelector('#portfolio-date').textContent.includes('Day 340'));assert.equal(await page.locator('.position-row').count(),18);pass('Big5 preview and partial merge advance Day once');
await page.click('#upload-open');await page.fill('#paste-text','code,name,ret,pnl,asOf\n0050,測試股票,,0,2026-10-07');await page.click('#recognize');await page.waitForSelector('#import-preview:not([hidden])');assert.ok(await page.locator('#older-warning').isVisible());await page.click('#commit-import');assert.ok(await page.locator('#upload-dialog').isVisible());await page.check('#accept-older');await page.check('input[name="import-mode"][value="replace"]');await page.click('#commit-import');await page.waitForFunction(()=>document.querySelectorAll('.position-row').length===1);assert.match(await page.locator('#portfolio-date').innerText(),/Day 340.*2026-10-07/);pass('older date blocked until accepted; full replacement preserves Day');
await page.click('#edit-portfolio');await page.fill('input[data-field="ret"]','6');await page.locator('#edit-form button[type="submit"],#edit-form button.primary').click();await page.waitForSelector('#edit-dialog:not([open])',{state:'attached'});assert.match(await page.locator('#positions').innerText(),/P2/);pass('manual edit writes and regroups');
await page.reload();await page.waitForSelector('#portfolio-tab:not([hidden])');pass('last tab persists');
for(const color of ['light','dark']){await page.emulateMedia({colorScheme:color});await page.evaluate(()=>{delete document.documentElement.dataset.theme;localStorage.removeItem('ark-theme');});await page.setViewportSize({width:400,height:860});for(const tab of ['portfolio','market']){await page.click(`[data-tab="${tab}"]`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),400);await page.screenshot({path:path.join(root,'tests',`mobile-${tab}-${color}.png`),fullPage:false});}pass('400px no horizontal overflow: '+color);}
await page.click('#chat-open');assert.ok(await page.locator('#chat').isVisible());assert.equal(await page.locator('#chat').evaluate(e=>Math.round(e.getBoundingClientRect().width)),400);await page.click('#chat-close');pass('mobile fullscreen chat');
// Mock the key status and transport only in this browser, never in the local app or persisted data.
await page.route('**/api/status',async route=>{const r=await route.fetch(),s=await r.json();await route.fulfill({json:{...s,aiConfigured:true}});});
await page.route('**/api/ask',async route=>{const {prompt}=route.request().postDataJSON();let text;if(prompt.includes('投資紀律教練'))text='測試用複盤文章。\n'+prompt.split('核對用固定水位清單：')[1].split('\n本期含水位')[0]+'\n這不是運氣，是紀律的回報。';else text='{"id":"buffett","stance":0,"reply":"從我這套框架看，這是測試用回覆；應先核對資料與安全邊際。"}\n';let body='';for(let i=0;i<text.length;i+=7)body+='event: delta\ndata: '+JSON.stringify({text:text.slice(i,i+7)})+'\n\n';body+='event: done\ndata: {}\n\n';await route.fulfill({contentType:'text/event-stream',body});});
await page.reload();await page.waitForSelector('.crew-card');await page.click('[data-person="buffett"]');await page.click('[data-ask-person="buffett"]');await page.fill('#chat-input','測試提問');await page.click('#chat-send');await page.waitForFunction(()=>document.querySelector('#chat-status').textContent.includes('本輪完成'));assert.equal(await page.locator('.chat-response').count(),1);await page.click('[data-like]');assert.equal(await page.locator('[data-like]').textContent(),'♥ 已按讚');await page.click('[data-follow]');assert.equal(await page.locator('.chat-person.active').count(),1);await page.click('[data-everyone]');assert.equal(await page.locator('.chat-person.active').count(),8);pass('mock-only NDJSON chat, typewriter, like, follow and group reply');
await page.click('#chat-close');await page.click('[data-tab="portfolio"]');await page.click('#journal-generate');await page.waitForFunction(()=>document.querySelector('#journal-status').textContent.includes('已存入'));assert.equal(await page.locator('.journal-history').count(),1);assert.ok(fs.existsSync(path.join(tmp,'journal/2026-10-07.json')));pass('mock-only journal streams, formats and persists');
assert.deepEqual(errors,[]);pass('no uncaught browser errors');fs.writeFileSync(path.join(root,'tests/browser-result.json'),JSON.stringify({checkedAt:new Date().toISOString(),checks,errors,realAI:false,note:'AI 回覆為隔離測試中的模擬串流，未呼叫 Anthropic；未改動正式庫存。'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.kill();fs.rmSync(tmp,{recursive:true,force:true});});
