import test from 'node:test';import assert from 'node:assert/strict';import {group,ndjsonParser,sseParser,rich,safeURL,mergePositions,consumeSSE} from '../lib.js';
test('ret percentage units and mutually exclusive groups',()=>assert.deepEqual([-22.73,-15,-8,0,5,null].map(ret=>group({ret},{p1:-15,p3:-8,p2:5})),['P1','P1','P3','正常持有','P2','待更新']));
test('NDJSON survives arbitrary chunks and non-newline final object',()=>{const results=[];const parser=ndjsonParser(x=>results.push(x));const text='{"id":"buffett","reply":"繁體中文"}\n{"id":"wei","reply":"台積電"}';for(let i=0;i<text.length;i+=2)parser.push(text.slice(i,i+2));parser.end();assert.equal(results[0].reply,'繁體中文');assert.equal(results[1].id,'wei');});
test('SSE survives every byte boundary incl CRLF',()=>{const results=[];const p=sseParser((e,o)=>results.push([e,o]));const t='event: delta\r\ndata: {"text":"你好"}\r\n\r\nevent: done\r\ndata: {}\r\n\r\n';for(const c of t)p.push(c);p.end();assert.deepEqual(results,[['delta',{text:'你好'}],['done',{}]]);});
test('incomplete SSE and malformed NDJSON rejected',()=>{const p=sseParser(()=>{});p.push('data: {"text":"x"}');assert.throws(()=>p.end());const n=ndjsonParser(()=>{});assert.throws(()=>n.push('not json\n'));});
test('safe markdown and URLs do not inject HTML',()=>{assert.equal(rich('**好**<img onerror="x">'),'<strong>好</strong>&lt;img onerror=&quot;x&quot;&gt;');assert.equal(safeURL('javascript:alert(1)'),'#');});
test('later nonempty values only; zero retained',()=>{const out=mergePositions([{code:'0056',ret:null,pnl:0,name:'原名'}],[{code:'0056',ret:5,pnl:null,name:''}]);assert.equal(out.length,1);assert.equal(out[0].pnl,0);assert.equal(out[0].ret,5);assert.equal(out[0].name,'原名');});

test('UTF-8 SSE survives split multibyte bytes',async()=>{const data=new TextEncoder().encode('event: delta\ndata: {"text":"臺灣繁體"}\n\nevent: done\ndata: {}\n\n');const stream=new ReadableStream({start(c){for(const b of data)c.enqueue(new Uint8Array([b]));c.close();}});let result='';await consumeSSE(new Response(stream),s=>result+=s);assert.equal(result,'臺灣繁體');});
test('missing completion event rejects partial stream',async()=>{await assert.rejects(consumeSSE(new Response('event: delta\ndata: {"text":"partial"}\n\n'),()=>{}),/串流未完成/);});
